jaap/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomLoginView,CustomLogoutView, home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('api/',include('autenticacion.urls')),
    path('api/',include('registro.urls')),
    path('api/', include('parameters.urls')),
    path('pagos/', include('pagos.urls')),
    path('reportes/', include('reportes.urls')),
    path('asignados/', include('asignados.urls')),
    path('api/auth/', include('dj_rest_auth.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

admin.site.site_url = "/reportes/dashboard"

pagos/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from .views import PagoCreateView, ObtenerInfoAbonadoView

urlpatterns = [
    path('', PagoCreateView.as_view(), name="realizar_pago"),
    path('obtener-info-abonado/', ObtenerInfoAbonadoView.as_view(), name='obtener_info'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

pagos/models.py
# pagos/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from autenticacion.models import Empleado, Abonado
from registro.models import Lectura

class Pago(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    abonado = models.ForeignKey(Abonado, on_delete=models.CASCADE)
    registro_consumo = models.ForeignKey(Lectura, on_delete=models.CASCADE)
    cantidad_total_pago = models.DecimalField(max_digits=10, decimal_places=2)
    total_abonado = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.empleado} - {self.abonado} - {self.fecha_creacion}"

def enviar_correo_pago(pago):

    data = {
        "registro_consumo": pago.registro_consumo,
        "cantidad_total_pago": pago.cantidad_total_pago,
        "total_abonado": pago.total_abonado,
        "fecha_creacion": pago.fecha_creacion
    }
    subject = 'Nuevo Pago Registrado'
    message = render_to_string('correo_pago.html', data)
    from_email = settings.EMAIL_HOST_USER
    to_email = [pago.abonado.email]  # Reemplaza con la dirección de correo a la que deseas enviar el correo
    print("ENVIANDO EMAIL PAGO")
    send_mail(subject, message, from_email, to_email, fail_silently=False)

@receiver(post_save, sender=Pago)
def lectura_post_save(sender, instance, **kwargs):
    print("Señal de post_save ejecutada para Lectura")
    enviar_correo_pago(instance)

pagos/forms.py
# pagos/forms.py
from django import forms
from .models import Pago
from autenticacion.models import Abonado
from registro.models import Lectura

class PagoForm(forms.ModelForm):
    abonado = forms.ModelChoiceField(queryset=Abonado.objects.all())
    ultima_info_consumo = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    ultima_info_pago = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    cantidad_total_pago = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = Pago
        fields = ['empleado', 'abonado', 'registro_consumo', 'cantidad_total_pago', 'total_abonado']

pagos/views.py
# pagos/views.py
from django.views.generic.edit import CreateView
from django.http import JsonResponse
from django.views import View
from django.shortcuts import get_object_or_404
from .models import Pago
from .forms import PagoForm
from registro.models import Lectura
from parameters.models import Parameter
from autenticacion.models import Abonado

class PagoCreateView(CreateView):
    model = Pago
    form_class = PagoForm
    template_name = 'pagos/pago_form.html'
    success_url = '/reportes/dashboard/'

class ObtenerInfoAbonadoView(View):
    def get(self, request, *args, **kwargs):
        abonado_id = request.GET.get('abonado_id')
        abonado = get_object_or_404(Abonado, pk=abonado_id)
        m3 = Parameter.objects.filter(codigo="PR-AG").first()

        total_a_pagar = 0

        # Obtener el último registro de consumo para el abonado
        ultimo_consumo = Lectura.objects.filter(abonado=abonado).order_by('fecha').last()
        consumo = 'No hay registros de consumo.' if not ultimo_consumo else str(ultimo_consumo.lectura_actual)

        if ultimo_consumo:
            total_a_pagar += (float(ultimo_consumo.lectura_actual - ultimo_consumo.lectura_anterior) * float(m3.valor))

        # Obtener el último pago para el abonado
        ultimo_pago = Pago.objects.filter(abonado=abonado).order_by('-fecha_creacion').first()
        pago = 'No hay registros de pago.' if not ultimo_pago else str(ultimo_pago.cantidad_total_pago)

        if ultimo_pago:
            total_a_pagar += round(float(ultimo_pago.cantidad_total_pago) - float(ultimo_pago.total_abonado),2)

        # Obtener las opciones actualizadas para el campo registro_consumo
        # opciones_registro_consumo = Lectura.objects.filter(abonado=abonado).values('id', 'lectura_actual')

        return JsonResponse({
            'ultimo_consumo': consumo,
            'ultimo_pago': pago,
            'opciones_registro_consumo':[
                {
                        'id': ultimo_consumo.id,
                        'str': ultimo_consumo.lectura_actual
                }
            ],
            'cantidad_total_pago': round(total_a_pagar,2)
        })

templates/pagos/pago_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pagos/css/styles.css' %}">

{% block content %}
  <div style="display: flex;justify-content: center;background-color: #007bff;margin:0 0 20px 0">
    <h1>Registrar Pago</h1>
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <!-- Agregar un campo oculto para almacenar la URL de la vista JSON -->
    <input type="hidden" id="url-info-abonado" value="{% url 'obtener_info' %}" />

    <div style="display: flex; justify-content: space-between;align-items: center;">
      <button type="submit">Registrar Pago</button>
    <a class="btn" href="{% url 'dashboard' %}" >Cancelar</a>
    </div>
  </form>

  <!-- Agregar scripts JavaScript -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    $(document).ready(function() {
      // Manejar el evento de cambio en el campo de selección de abonados
      $('#id_abonado').change(function() {
        // Obtener el ID del abonado seleccionado
        var abonadoId = $(this).val();
        // Obtener la URL de la vista JSON
        var urlInfoAbonado = $('#url-info-abonado').val();

        // Realizar una solicitud AJAX para obtener la información del abonado
        $.ajax({
          url: urlInfoAbonado,
          data: { abonado_id: abonadoId },
          dataType: 'json',
          success: function(data) {
            // Actualizar los campos con la información obtenida
            console.log(data)
            $('#id_ultima_info_consumo').val(data.ultimo_consumo);
            $('#id_ultima_info_pago').val(data.ultimo_pago);
            $('#id_cantidad_total_pago').val(data.cantidad_total_pago);
            
            // Actualizar el campo registro_consumo
            $('#id_registro_consumo').empty(); // Limpiar opciones actuales
            $.each(data.opciones_registro_consumo, function(index, value) {
              $('#id_registro_consumo').append($('<option>', {
                value: value.id,
                text: value.str
              }));
            });
            $('#id_registro_consumo').val(data.opciones_registro_consumo[0].id);
          }
        });
      });
    });
  </script>
{% endblock %}